/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MastermindRouteImport } from './routes/mastermind'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EbookRouteImport } from './routes/ebook'
import { Route as CourseRouteImport } from './routes/course'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BooksRouteImport } from './routes/books'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as AboutMarcRouteImport } from './routes/about-marc'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PurchaseSuccessRouteImport } from './routes/purchase/success'
import { Route as PurchaseEbookThankYouRouteImport } from './routes/purchase/ebook-thank-you'
import { Route as PurchaseCourseUpsellRouteImport } from './routes/purchase/course-upsell'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedBrotherhoodRouteImport } from './routes/_authenticated/brotherhood'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiSamcartWebhookRouteImport } from './routes/api/samcart/webhook'
import { Route as AuthenticatedCoursesSlugRouteImport } from './routes/_authenticated/courses_.$slug'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MastermindRoute = MastermindRouteImport.update({
  id: '/mastermind',
  path: '/mastermind',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookRoute = EbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMarcRoute = AboutMarcRouteImport.update({
  id: '/about-marc',
  path: '/about-marc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseSuccessRoute = PurchaseSuccessRouteImport.update({
  id: '/purchase/success',
  path: '/purchase/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseEbookThankYouRoute = PurchaseEbookThankYouRouteImport.update({
  id: '/purchase/ebook-thank-you',
  path: '/purchase/ebook-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseCourseUpsellRoute = PurchaseCourseUpsellRouteImport.update({
  id: '/purchase/course-upsell',
  path: '/purchase/course-upsell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrotherhoodRoute =
  AuthenticatedBrotherhoodRouteImport.update({
    id: '/brotherhood',
    path: '/brotherhood',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSamcartWebhookRoute = ApiSamcartWebhookRouteImport.update({
  id: '/api/samcart/webhook',
  path: '/api/samcart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCoursesSlugRoute =
  AuthenticatedCoursesSlugRouteImport.update({
    id: '/courses_/$slug',
    path: '/courses/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-marc': typeof AboutMarcRoute
  '/blueprint': typeof BlueprintRoute
  '/books': typeof BooksRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/ebook': typeof EbookRoute
  '/login': typeof LoginRoute
  '/mastermind': typeof MastermindRoute
  '/reset-password': typeof ResetPasswordRoute
  '/testimonials': typeof TestimonialsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/brotherhood': typeof AuthenticatedBrotherhoodRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/purchase/course-upsell': typeof PurchaseCourseUpsellRoute
  '/purchase/ebook-thank-you': typeof PurchaseEbookThankYouRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/api/samcart/webhook': typeof ApiSamcartWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-marc': typeof AboutMarcRoute
  '/blueprint': typeof BlueprintRoute
  '/books': typeof BooksRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/ebook': typeof EbookRoute
  '/login': typeof LoginRoute
  '/mastermind': typeof MastermindRoute
  '/reset-password': typeof ResetPasswordRoute
  '/testimonials': typeof TestimonialsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/account': typeof AuthenticatedAccountRoute
  '/brotherhood': typeof AuthenticatedBrotherhoodRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/purchase/course-upsell': typeof PurchaseCourseUpsellRoute
  '/purchase/ebook-thank-you': typeof PurchaseEbookThankYouRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/courses/$slug': typeof AuthenticatedCoursesSlugRoute
  '/api/samcart/webhook': typeof ApiSamcartWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about-marc': typeof AboutMarcRoute
  '/blueprint': typeof BlueprintRoute
  '/books': typeof BooksRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/course': typeof CourseRoute
  '/ebook': typeof EbookRoute
  '/login': typeof LoginRoute
  '/mastermind': typeof MastermindRoute
  '/reset-password': typeof ResetPasswordRoute
  '/testimonials': typeof TestimonialsRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/brotherhood': typeof AuthenticatedBrotherhoodRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/purchase/course-upsell': typeof PurchaseCourseUpsellRoute
  '/purchase/ebook-thank-you': typeof PurchaseEbookThankYouRoute
  '/purchase/success': typeof PurchaseSuccessRoute
  '/_authenticated/courses_/$slug': typeof AuthenticatedCoursesSlugRoute
  '/api/samcart/webhook': typeof ApiSamcartWebhookRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-marc'
    | '/blueprint'
    | '/books'
    | '/community'
    | '/contact'
    | '/course'
    | '/ebook'
    | '/login'
    | '/mastermind'
    | '/reset-password'
    | '/testimonials'
    | '/update-password'
    | '/account'
    | '/brotherhood'
    | '/courses'
    | '/dashboard'
    | '/purchase/course-upsell'
    | '/purchase/ebook-thank-you'
    | '/purchase/success'
    | '/courses/$slug'
    | '/api/samcart/webhook'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-marc'
    | '/blueprint'
    | '/books'
    | '/community'
    | '/contact'
    | '/course'
    | '/ebook'
    | '/login'
    | '/mastermind'
    | '/reset-password'
    | '/testimonials'
    | '/update-password'
    | '/account'
    | '/brotherhood'
    | '/courses'
    | '/dashboard'
    | '/purchase/course-upsell'
    | '/purchase/ebook-thank-you'
    | '/purchase/success'
    | '/courses/$slug'
    | '/api/samcart/webhook'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about-marc'
    | '/blueprint'
    | '/books'
    | '/community'
    | '/contact'
    | '/course'
    | '/ebook'
    | '/login'
    | '/mastermind'
    | '/reset-password'
    | '/testimonials'
    | '/update-password'
    | '/_authenticated/account'
    | '/_authenticated/brotherhood'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/purchase/course-upsell'
    | '/purchase/ebook-thank-you'
    | '/purchase/success'
    | '/_authenticated/courses_/$slug'
    | '/api/samcart/webhook'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutMarcRoute: typeof AboutMarcRoute
  BlueprintRoute: typeof BlueprintRoute
  BooksRoute: typeof BooksRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CourseRoute: typeof CourseRoute
  EbookRoute: typeof EbookRoute
  LoginRoute: typeof LoginRoute
  MastermindRoute: typeof MastermindRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TestimonialsRoute: typeof TestimonialsRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
  PurchaseCourseUpsellRoute: typeof PurchaseCourseUpsellRoute
  PurchaseEbookThankYouRoute: typeof PurchaseEbookThankYouRoute
  PurchaseSuccessRoute: typeof PurchaseSuccessRoute
  ApiSamcartWebhookRoute: typeof ApiSamcartWebhookRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mastermind': {
      id: '/mastermind'
      path: '/mastermind'
      fullPath: '/mastermind'
      preLoaderRoute: typeof MastermindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook': {
      id: '/ebook'
      path: '/ebook'
      fullPath: '/ebook'
      preLoaderRoute: typeof EbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course': {
      id: '/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof CourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-marc': {
      id: '/about-marc'
      path: '/about-marc'
      fullPath: '/about-marc'
      preLoaderRoute: typeof AboutMarcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/success': {
      id: '/purchase/success'
      path: '/purchase/success'
      fullPath: '/purchase/success'
      preLoaderRoute: typeof PurchaseSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/ebook-thank-you': {
      id: '/purchase/ebook-thank-you'
      path: '/purchase/ebook-thank-you'
      fullPath: '/purchase/ebook-thank-you'
      preLoaderRoute: typeof PurchaseEbookThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/course-upsell': {
      id: '/purchase/course-upsell'
      path: '/purchase/course-upsell'
      fullPath: '/purchase/course-upsell'
      preLoaderRoute: typeof PurchaseCourseUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brotherhood': {
      id: '/_authenticated/brotherhood'
      path: '/brotherhood'
      fullPath: '/brotherhood'
      preLoaderRoute: typeof AuthenticatedBrotherhoodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/samcart/webhook': {
      id: '/api/samcart/webhook'
      path: '/api/samcart/webhook'
      fullPath: '/api/samcart/webhook'
      preLoaderRoute: typeof ApiSamcartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/courses_/$slug': {
      id: '/_authenticated/courses_/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof AuthenticatedCoursesSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedBrotherhoodRoute: typeof AuthenticatedBrotherhoodRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCoursesSlugRoute: typeof AuthenticatedCoursesSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedBrotherhoodRoute: AuthenticatedBrotherhoodRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCoursesSlugRoute: AuthenticatedCoursesSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutMarcRoute: AboutMarcRoute,
  BlueprintRoute: BlueprintRoute,
  BooksRoute: BooksRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CourseRoute: CourseRoute,
  EbookRoute: EbookRoute,
  LoginRoute: LoginRoute,
  MastermindRoute: MastermindRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TestimonialsRoute: TestimonialsRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
  PurchaseCourseUpsellRoute: PurchaseCourseUpsellRoute,
  PurchaseEbookThankYouRoute: PurchaseEbookThankYouRoute,
  PurchaseSuccessRoute: PurchaseSuccessRoute,
  ApiSamcartWebhookRoute: ApiSamcartWebhookRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
